image: maven:latest

variables:
  SOME_VAR: "some value"

stages:
  - build
  - test
  - sonarqube
  - deploy

before_script:
  - echo "Start CI/CD"

build:
  stage: build
  script:
    - echo "Build process"
    - cd he-f1
    - mvn clean package -Dmaven.test.skip=true
    - echo "Build ok"
  only:
    - dev
  tags:
    - alpine-docker

unittest:
  stage: test
  script:
    - echo "start test"
    # remove sql related bugs
    - cd he-f1 && rm ./he-f1/src/main/resources/data.sql
    - mvn test
    - echo "test ok"
  only:
    - dev
  tags:
    - alpine-docker

sonarqube:
  stage: sonarqube
  script:
    - echo "start sonarqube stage"
    - cd he-f1
    - /opt/apache-maven-3.6.3/bin/mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - echo "sonarqube ok"
  only:
    - dev
  tags:
    - he-f1-prod

deploy:
  stage: deploy
  before_script:
    - echo "do some stuff before"
  script:
    - echo "deploy HE-F1"
    - cd he-f1
    - docker-compose down
    - docker-compose up -d
    - echo "deploy ok"
  only:
    - dev
  tags:
    - he-f1-prod
  when: manual

after_script:
  - echo "End CI/CD"
