#image: ubuntu
image: maven:latest

variables:
  SOME_VAR: "some value"

stages:
  - build
  - test
  - sonarqube
  - deploy

before_script:
  - echo "Start CI/CD"
  # - echo "SOME_VAR = $SOME_VAR" # calls my custom variable
  # - echo $CI_JOB_STAGE # calls a predefined variable -  https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
  # - echo $CI_COMMIT_SHORT_SHA # calls another predefined variable

# build:
#   stage: build
#   script:
#     - echo "Build process"
#     # - cd he-f1
#     # - mvn clean package -Dmaven.test.skip=true
#     - echo "Build ok"
#   only:
#     - update-ci-cd
#   tags:
#     - alpine-docker

# unittest:
#   stage: test
#   script:
#     - echo "start test"
#     - echo "test ok"
#   only:
#     - update-ci-cd
#   tags:
#     - alpine-docker

# katalon_test_suite:
#   stage: test
#   script:
#     - echo "start katalon test suite"
#     - echo "katalon test suite ok"
#   only:
#     - update-ci-cd
#   tags:
#     - alpine-docker

# sonarqube:
#   stage: sonarqube
#   script:
#     - echo "start sonarqube stage"
#     - echo "sonarqube ok"
#   only:
#     - update-ci-cd
#   tags:
#     - alpine-docker

deploy:
  stage: deploy
  before_script:
    - echo "do some stuff before"
  script:
    - echo "deploy HE-F1"
    - cd he-f1
    - docker-compose down
    - docker-compose up -d
    - echo "deploy ok"
  only:
    - update-ci-cd
  tags:
    - he-f1-prod
  when: manual

after_script:
  - echo "End CI/CD"
